### ISSUE TITLE
Use axiosMaker to configure future requests

### ISSUE THREAD

**Issue by johnlindquist** [eggheadio/egghead-io-nextjs#14]
Jared strongly recommended axios and the "axiosMaker" workflow to save us from configuring headers with every request:

I'm pretty sure that's the same thing as the `axios.create` API:

https://github.com/axios/axios#creating-an-instance

**Comment by joelhooks** [comment]
we have a `useRequest` hook that does something similar, but with react-query behind the scenes instead of useSwr. Basically a service layer wrapping axios or whatever. I think our SSR is going to avoid auth entirely so it should be fairly straight forward, though we have capabilities to make auth'd SSR calls via cookie currently.
